name: Build PDF Preview on all Branches

on:
  push:
    branches:
      - '**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango-1.0-0 libpangocairo-1.0-0 libcairo2 libgdk-pixbuf2.0-0 libffi-dev
          pip install markdown weasyprint

      - name: Generate PDF
        run: python ./scripts/generate_pdf_preview.py source/latest ./combined_draft_latest.pdf
        working-directory: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: Draft-PDF
          path: combined_draft.pdf
